---
- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: yes
  with_items:
    - apt-transport-https

- name: Debian repo key on package cloud
  apt_key:
    url: "{{ grafana_key }}"

- name: Debian grafana repo
  apt_repository:
    repo: "{{ grafana_repo }}"

- name: Install grafana
  apt:
    pkg: grafana
    state: present

- name: Links grafana dir to /
  file:
    src: /etc/grafana
    dest: /grafana
    state: link
    force: yes
    owner: grafana
    group: grafana

- name: Copy configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/grafana/{{ item }}"
    owner: grafana
    group: grafana
  notify: restart grafana
  with_items:
    - ldap.toml
    - grafana.ini

- name: Ensure grafana is started and enabled on boot
  service:
    name: grafana-server
    enabled: yes
    state: running

# As far as I know, there is no possible way on Ansible to template out a file into a variable
# There is no way to lookup a remote file either.

#- name: Template out Dashboards
#  template:
#    src: "{{ item.0.dashboard }}.j2"
#    dest: "/tmp/{{ item.1 }}_{{ item.0.dashboard }}"
#  with_subelements:
#    - "{{ grafana_dashboards | default('[]') }}"
#    - hosts
#  delegate_to: localhost
#  when: grafana_token is defined and grafana_dashboards is defined

- name: Import dashboards
  uri:
    url: "http://{{ ansible_nodename }}:8080/api/dashboards/db"
    method: POST
    HEADER_Accept: application/json
    HEADER_Content-Type: application/json
    HEADER_Authorization: "Bearer {{ grafana_token }}"
    body: "{{ lookup('file', item.0.dashboard ) }}"
    body_format: json
    response: 200
  with_subelements:
    - "{{ grafana_dashboards|default('[]') }}"
    - hosts
  when: grafana_token is defined and grafana_dashboards is defined
