---

- name: GRAFANA | Install
  include: install.yml
  tags:
    - install

- name: GRAFANA | Configure
  include: config.yml
  tags:
    - configure

- name: GRAFANA | Service
  include: service.yml
  tags:
    - service

- name: GRAFANA | Datasource
  include: datasource.yml
  tags:
    - datasource

- name: GRAFANA | Dashboards
  include: dashboards.yml
  tags:
    - dashboards
